name: to_do
description: "A bus tracking application with real-time updates"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI components
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.0
  animated_text_kit: ^4.2.2
  webview_flutter: ^4.11.0

  # State management
  provider: ^6.1.1
  
  # Network and Data
  http: ^1.2.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  
  # Maps and Location
  google_maps_flutter: ^2.5.0
  location: ^8.0.0
  geocoding: ^3.0.0
  geolocator: ^13.0.4
  flutter_polyline_points: ^2.1.0
  
  # Socket connection
  socket_io_client: ^3.1.1
  
  # Others
  intl: ^0.19.0
  permission_handler: ^11.0.1
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.2
  flutter_local_notifications: ^16.3.3
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

  generate: true  # This is crucial for localizations
